### ISSUE TITLE
Potential typo ?

### ISSUE THREAD

**Issue by ABohynDOE** [pbloem/pca-book#1]
First of all, great work ! I really enjoy reading the book ! 
On this line, you say that "Can we work out which choice of $x_i$ on the line will minimize the reconstruction error ?"

https://github.com/pbloem/pca-book/blob/ba083f9a27965b16e2321be539005e89ed5a35f4/chapter1.tex#L138

Isn't it supposed to be $x^{\prime}_i$ instead of $x_i$ ?
My intuition is that $x_i$ is fixed since it is the data, and that $x^{\prime}_i$ is defined by the vector $\omega$, so modifying $\omega$ modifies $x_i$, and thus can decrease the reconstruction error.
I'm not an expert in PCA so it might be wrong.

**Comment by pbloem** [comment]
Hi, thanks for the pointer. I think this is fixed in the latest version.
